name: ligo
channels:
    - conda-forge
    - defaults
dependencies:
    - numpy = 1.16
    - scipy = 1.2
    - h5py = 2.10
    - matplotlib = 2.2
    - python = 2.7
    - decorator = 4.4
    - ipykernel = 4.8